[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[package.metadata.ecos]
ecos_project_root = true
ecos_flash_cmd_to = "{{device_path}}"

[dependencies]
ecos-ssc1 = { version = "0", features = ["panic-trace"] }

[build-dependencies]
cc = "1"
