[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[package.metadata.ecos]
ecos_project_root = true

[dependencies]
ecos-ssc1 = "0"

[build-dependencies]
cc = "1"
